springfoxdocumentation:
  swagger:
    v2:
      path: /api-docs
      
server:
  port: ${PETSTOREORDERSERVICE_SERVER_PORT:8080}

petstore:
  service:
    product:
      url: ${PETSTOREPRODUCTSERVICE_URL:http://localhost:8082}

#azure:
#  application-insights:
#      instrumentation-key: ${PETSTORESERVICES_AI_INSTRUMENTATION_KEY}
      
spring:
  application:
    name: petstoreorderservice
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    azure:
      cosmos:
        database: ${AZURE_COSMOS_DATABASE_NAME}

azure:
  cosmosdb:
    uri: ${AZURE_COSMOS_ENDPOINT}
    key: ${AZURE_COSMOS_KEY}
    database: ${AZURE_COSMOS_DATABASE_NAME}

management:
  endpoints:
    web:
      exposure:
        include: "*"       
  trace:
    http:
      enabled: true 
  endpoint:
    httptrace:
      enabled: true
